# Generated by Django 3.2.12 on 2023-07-07 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='order',
            new_name='ordernumber',
        ),
    ]
