# Generated by Django 4.2.1 on 2023-06-18 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_created=True)),
                ('orderStatus', models.CharField(max_length=32)),
                ('deliveryCost', models.DecimalField(decimal_places=2, max_digits=6)),
                ('deliveryMethod', models.CharField(max_length=32)),
                ('deliveryPersonName', models.CharField(max_length=32)),
                ('deliveryDuration', models.DurationField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
