# Generated by Django 3.2.12 on 2023-07-07 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipping',
            name='shippingLocation',
            field=models.CharField(max_length=32),
        ),
    ]
