# Generated by Django 3.2.12 on 2023-07-07 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0006_remove_order_shippings'),
        ('shipping', '0002_alter_shipping_shippinglocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipping',
            name='order',
            field=models.ManyToManyField(to='Order.Order'),
        ),
    ]
