# Generated by Django 3.2.12 on 2023-07-07 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_rename_order_payment_ordernumber'),
        ('Order', '0002_alter_order_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='payments.payment'),
        ),
    ]
