# Generated by Django 3.2.12 on 2023-07-07 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0001_initial'),
        ('Order', '0004_order_vendors'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='Shippings',
            field=models.ManyToManyField(to='shipping.Shipping'),
        ),
    ]
